# Generated by Django 6.1 on 2026-09-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ph_no', models.CharField(max_length=10)),
                ('roll_no', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
